Надо исправить
--------------

||Не надо на 2 метода разбивать получение аватары и получение имени и прочего. Вы делаете лишний запрос к серверу, каждый раз
||получая новые данные, теперь представьте что это популярный ресурс -- вуаля, вы уже задвоили количество запросов
||и нагрузка возросла.

Логика класса UserInfo должна быть, например, такая -- есть метод получения юзеринфо (например, getPerson) с сервера,
он получает сразу id, аватар, имя, профессию и имя любимой кошки. И сохраняет внутри объекта. Когда вам нужно
узнать url аватара, вы запрашиваете метод getAvatar() который вернет вам сохраненный внутри объекта класса адрес,
по аналогии, например, getName -- вернет объект с именем и профессией, но брать их будет тоже внутри объекта класса.

Обновлять данные внутри объекта будем только когда пользователь успешно изменил информацию о себе, или об аватаре.


Но, самая главная беда в том что вы не тестируете скрипт как я попросил. Загрузите страницу. Отключите интеренет
и посмотрите в консоль когда будете профиль менять. Ваш catch срабатывает на на переданную ошибку Api, а на ошибку
в идущем перед ним then. Смотрите:

apiGetName().then((res) => { // ошибка возникает здесь
      this.nameProfile.textContent = res.name;
      this.jobProfile.textContent = res.about;
    })
    .catch( (res) => {
      // выводит в консоль ошибку что res is undefined, т.е. мы не передали ошибку сервера,
      // а создали вообще другую, новую, на 3 строки выше
      console.log(res); 
    })

Почему? А вот:

  getUserInfo() {
    return fetch(`${this.options.baseUrl}/users/me`, {
      headers: {
        authorization: `${this.options.headers.authorization}`,
      }
    })
      .then(res => {
        if (res.ok) {
          return res.json();
        } else {
          return Promise.reject(`Error ${res.status}`);
        }
      })
      .then((res) => {
        return res
      })
      .catch((err) => {
        //
        // Вот тут после console.log вы должны вернуть Promise.reject
        // через return а не просто в воздухе выполнить
        // Потому что ваш catch НИЧЕГО кроме вывода в консоль не делает и самое главное,
        // не сообщает дальше за пределы Api что есть ошибка, он просто возвращает "ничего"
        // поэтому получая его apiGetName().then((res) => .... вы получаете пустоту,
        // скрипт падает, его подхватывает следующий catch но он по сути борется с последствиями.
        //
        console.log(err);
        // Во все catch Api добавьте вот такую строку -- и тогда в консоли больше не будет ругани на undefined переменные
        // return Promise.reject(new Error(`Ошибка ${err.message}`));
      })
  };

Поправьте обработку ВЕЗДЕ.

Про это я писал вам в прошлом ревью:

  catch тоже должен либо пробрасывать ошибку через throw, либо возвращать промис с ошибкой

Жаль что вы не уделили должного внимания



Можно лучше
-----------

Лайки считаются, но при загрузке карточек с сервера "лайкнутые" карточки не получают закрашенное "сердечко".


Промежуточный итог
------------------

Лайки круто, попапы не закрываются раньше времени -- это тоже отлично, но нам с вами надо перестать генерировать новые ошибки
при обращении к Api, а начать обрабатывать полученные. Также надо оптимизировать UserInfo чтобы он не отправлял лишних запросов
на сервер. Совсем немного осталось, исправляйте и присылайте!
